import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

type Lang = 'es' | 'en'

const translations = {
  es: {
    nav_home: 'Inicio', nav_mycvs: 'Mis CVs', nav_login: 'Iniciar sesión',
    nav_register: 'Registrarse', nav_settings: 'Ajustes', nav_logout: 'Cerrar sesión',
    hero_title_1: 'Convierte cualquier', hero_title_2: 'oferta de trabajo',
    hero_title_3: 'en tu CV perfecto',
    hero_sub: 'Pega una oferta de empleo y nuestra IA crea un CV optimizado para esa posición.',
    hero_btn: 'Comenzar gratis',
    login_title: 'Iniciar sesión', login_email: 'Correo electrónico', login_pass: 'Contraseña',
    login_btn: 'Entrar', login_loading: 'Entrando...',
    login_no_account: '¿No tienes cuenta?', login_register_link: 'Regístrate',
    login_err_conn: 'Error de conexión', login_err_creds: 'Credenciales incorrectas',
    reg_title: 'Crear cuenta', reg_name: 'Nombre', reg_last: 'Apellidos',
    reg_email: 'Correo electrónico', reg_pass: 'Contraseña', reg_pass_confirm: 'Repetir contraseña',
    reg_btn: 'Crear cuenta', reg_loading: 'Registrando...',
    reg_has_account: '¿Ya tienes cuenta?', reg_login_link: 'Inicia sesión',
    reg_err_pass: 'Las contraseñas no coinciden', reg_err_conn: 'Error de conexión',
    hist_title: 'Mis CVs', hist_new: '+ Nuevo CV', hist_loading: 'Cargando historial...',
    hist_not_found: 'no se han encontrado CVs', hist_retry: 'Reintentar',
    hist_empty: 'Todavía no has generado ningún CV.',
    hist_delete_confirm: '¿Seguro que quieres eliminar este CV?',
    hist_delete_err: 'No se pudo eliminar: ',
    form_step: 'Paso', form_of: 'de',
    pd_title: 'Datos personales', pd_name: 'Nombre', pd_last: 'Apellido',
    pd_email: 'Email', pd_phone: 'Teléfono', pd_address: 'Dirección',
    pd_postal: 'Código Postal', pd_city: 'Localidad',
    pd_license: 'Permiso de conducir', pd_license_sub: 'Incluir en el CV',
    pd_required: 'Obligatorio', pd_next: 'Siguiente',
    edu_title: 'Educación', edu_optional: 'Opcional', edu_degree: 'Título obtenido',
    edu_institution: 'Institución', edu_start: 'Inicio', edu_end: 'Fin',
    edu_month: 'Mes', edu_year: 'Año', edu_current: 'Actualidad',
    edu_add: '+ Agregar educación', edu_back: 'Atrás', edu_next: 'Siguiente',
    months: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    cert_title: 'Certificaciones', cert_cert: 'Certificación', cert_issue: 'Expedición',
    cert_add: '+ Agregar certificación', cert_back: 'Atrás', cert_next: 'Siguiente',
    exp_title: 'Experiencia', exp_role: 'Cargo', exp_company: 'Empresa',
    exp_start: 'Inicio', exp_end: 'Fin', exp_current: 'Actualidad',
    exp_add: '+ Agregar experiencia', exp_back: 'Atrás', exp_next: 'Siguiente',
    lang_title: 'Idiomas', lang_language: 'Idioma', lang_level: 'Nivel',
    lang_basic: 'Básico', lang_intermediate: 'Intermedio', lang_advanced: 'Avanzado', lang_native: 'Nativo',
    lang_add: '+ Agregar idioma', lang_back: 'Atrás', lang_next: 'Siguiente',
    skills_title: 'Skills', skills_sub: 'Añade tus habilidades técnicas o personales',
    skills_placeholder: 'Ej: JavaScript, Trabajo en equipo...',
    skills_back: 'Atrás', skills_next: 'Siguiente',
    offer_title: 'Oferta de trabajo',
    offer_sub: 'Pega aquí la oferta a la que quieres aplicar para personalizar tu CV',
    offer_company: 'Empresa', offer_desc_label: 'Descripción de la oferta',
    offer_desc_placeholder: 'Pega aquí el texto de la oferta de trabajo...',
    offer_back: 'Atrás', offer_next: 'Siguiente',
    photo_title: 'Foto de perfil', photo_sub: '¿Quieres añadir una foto a tu CV?',
    photo_yes: 'Sí, añadir foto', photo_no: 'Sin foto',
    photo_upload: 'Subir foto', photo_back: 'Atrás', photo_next: 'Siguiente',
    tpl_title: 'Elige tu plantilla', tpl_with_photo: 'Vista con foto de perfil',
    tpl_no_photo: 'Vista sin foto de perfil', tpl_back: 'Atrás', tpl_generate: 'Generar CV',
    tpl_generating: 'Generando tu CV…',
    tpl_euro_desc: 'Formato oficial europeo', tpl_mini_desc: 'Limpio y sencillo',
    tpl_mod_desc: 'Dark sidebar con acento verde',
    settings_title: 'Ajustes', settings_back: '← Volver', settings_loading: 'Cargando...',
    settings_personal_title: 'Datos personales', settings_personal_desc: 'Actualiza tu nombre y apellidos',
    settings_name: 'Nombre', settings_last: 'Apellidos', settings_email: 'Email',
    settings_email_hint: 'El email no se puede cambiar',
    settings_save: 'Guardar cambios', settings_saving: 'Guardando...',
    settings_pass_title: 'Contraseña', settings_pass_desc: 'Cambia tu contraseña de acceso',
    settings_pass_current: 'Contraseña actual', settings_pass_new: 'Nueva contraseña',
    settings_pass_repeat: 'Repetir contraseña',
    settings_pass_change: 'Cambiar contraseña', settings_pass_changing: 'Cambiando...',
    settings_delete_desc: 'Se eliminarán tu cuenta y todos tus CVs permanentemente',
    settings_delete_btn: 'Eliminar cuenta',
    settings_modal_title: '¿Eliminar cuenta?',
    settings_modal_text: 'Esta acción es irreversible. Se eliminarán tu cuenta y todos tus CVs permanentemente.',
    settings_modal_cancel: 'Cancelar', settings_modal_confirm: 'Sí, eliminar',
    settings_modal_deleting: 'Eliminando...',
    settings_toast_saved: 'Datos actualizados correctamente',
    settings_toast_save_err: 'Error al guardar los datos',
    settings_toast_pass_changed: 'Contraseña actualizada correctamente',
    settings_toast_pass_err: 'Error al cambiar contraseña',
    settings_toast_pass_nomatch: 'Las contraseñas no coinciden',
    settings_toast_pass_short: 'La contraseña debe tener al menos 3 caracteres',
    settings_toast_conn: 'Error de conexión',
    settings_toast_profile_err: 'Error al cargar el perfil',
    settings_toast_delete_err: 'Error al eliminar la cuenta',
    settings_name_placeholder: 'Tu nombre', settings_last_placeholder: 'Tus apellidos',
  },
  en: {
    nav_home: 'Home', nav_mycvs: 'My CVs', nav_login: 'Sign in',
    nav_register: 'Sign up', nav_settings: 'Settings', nav_logout: 'Sign out',
    hero_title_1: 'Turn any', hero_title_2: 'job offer',
    hero_title_3: 'into your perfect CV',
    hero_sub: 'Paste a job listing and our AI builds a CV optimised for that position.',
    hero_btn: 'Get started free',
    login_title: 'Sign in', login_email: 'Email address', login_pass: 'Password',
    login_btn: 'Sign in', login_loading: 'Signing in...',
    login_no_account: "Don't have an account?", login_register_link: 'Sign up',
    login_err_conn: 'Connection error', login_err_creds: 'Invalid credentials',
    reg_title: 'Create account', reg_name: 'First name', reg_last: 'Last name',
    reg_email: 'Email address', reg_pass: 'Password', reg_pass_confirm: 'Repeat password',
    reg_btn: 'Create account', reg_loading: 'Creating...',
    reg_has_account: 'Already have an account?', reg_login_link: 'Sign in',
    reg_err_pass: 'Passwords do not match', reg_err_conn: 'Connection error',
    hist_title: 'My CVs', hist_new: '+ New CV', hist_loading: 'Loading history...',
    hist_not_found: 'No CVs found', hist_retry: 'Retry',
    hist_empty: "You haven't generated any CV yet.",
    hist_delete_confirm: 'Are you sure you want to delete this CV?',
    hist_delete_err: 'Could not delete: ',
    form_step: 'Step', form_of: 'of',
    pd_title: 'Personal details', pd_name: 'First name', pd_last: 'Last name',
    pd_email: 'Email', pd_phone: 'Phone', pd_address: 'Address',
    pd_postal: 'Postal code', pd_city: 'City',
    pd_license: "Driver's licence", pd_license_sub: 'Include in CV',
    pd_required: 'Required', pd_next: 'Next',
    edu_title: 'Education', edu_optional: 'Optional', edu_degree: 'Degree obtained',
    edu_institution: 'Institution', edu_start: 'Start', edu_end: 'End',
    edu_month: 'Month', edu_year: 'Year', edu_current: 'Present',
    edu_add: '+ Add education', edu_back: 'Back', edu_next: 'Next',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    cert_title: 'Certifications', cert_cert: 'Certification', cert_issue: 'Issue date',
    cert_add: '+ Add certification', cert_back: 'Back', cert_next: 'Next',
    exp_title: 'Experience', exp_role: 'Job title', exp_company: 'Company',
    exp_start: 'Start', exp_end: 'End', exp_current: 'Present',
    exp_add: '+ Add experience', exp_back: 'Back', exp_next: 'Next',
    lang_title: 'Languages', lang_language: 'Language', lang_level: 'Level',
    lang_basic: 'Basic', lang_intermediate: 'Intermediate', lang_advanced: 'Advanced', lang_native: 'Native',
    lang_add: '+ Add language', lang_back: 'Back', lang_next: 'Next',
    skills_title: 'Skills', skills_sub: 'Add your technical or personal skills',
    skills_placeholder: 'e.g. JavaScript, Teamwork...',
    skills_back: 'Back', skills_next: 'Next',
    offer_title: 'Job offer',
    offer_sub: 'Paste the job offer you want to apply to so we can tailor your CV',
    offer_company: 'Company', offer_desc_label: 'Job description',
    offer_desc_placeholder: 'Paste the job offer text here...',
    offer_back: 'Back', offer_next: 'Next',
    photo_title: 'Profile photo', photo_sub: 'Do you want to add a photo to your CV?',
    photo_yes: 'Yes, add photo', photo_no: 'No photo',
    photo_upload: 'Upload photo', photo_back: 'Back', photo_next: 'Next',
    tpl_title: 'Choose your template', tpl_with_photo: 'View with profile photo',
    tpl_no_photo: 'View without profile photo', tpl_back: 'Back', tpl_generate: 'Generate CV',
    tpl_generating: 'Generating your CV…',
    tpl_euro_desc: 'Official European format', tpl_mini_desc: 'Clean and simple',
    tpl_mod_desc: 'Dark sidebar with green accent',
    settings_title: 'Settings', settings_back: '← Back', settings_loading: 'Loading...',
    settings_personal_title: 'Personal details', settings_personal_desc: 'Update your name and last name',
    settings_name: 'First name', settings_last: 'Last name', settings_email: 'Email',
    settings_email_hint: 'Email cannot be changed',
    settings_save: 'Save changes', settings_saving: 'Saving...',
    settings_pass_title: 'Password', settings_pass_desc: 'Change your access password',
    settings_pass_current: 'Current password', settings_pass_new: 'New password',
    settings_pass_repeat: 'Repeat password',
    settings_pass_change: 'Change password', settings_pass_changing: 'Changing...',
    settings_delete_desc: 'Your account and all your CVs will be permanently deleted',
    settings_delete_btn: 'Delete account',
    settings_modal_title: 'Delete account?',
    settings_modal_text: 'This action is irreversible. Your account and all your CVs will be permanently deleted.',
    settings_modal_cancel: 'Cancel', settings_modal_confirm: 'Yes, delete',
    settings_modal_deleting: 'Deleting...',
    settings_toast_saved: 'Details updated successfully',
    settings_toast_save_err: 'Error saving details',
    settings_toast_pass_changed: 'Password updated successfully',
    settings_toast_pass_err: 'Error changing password',
    settings_toast_pass_nomatch: 'Passwords do not match',
    settings_toast_pass_short: 'Password must be at least 3 characters',
    settings_toast_conn: 'Connection error',
    settings_toast_profile_err: 'Error loading profile',
    settings_toast_delete_err: 'Error deleting account',
    settings_name_placeholder: 'Your first name', settings_last_placeholder: 'Your last name',
  }
}

export type Translations = typeof translations['es']

export const useLangStore = defineStore('lang', () => {
  const savedLang = localStorage.getItem('lang') as Lang | null
  const lang = ref<Lang>(savedLang || 'es')

  const t = computed((): Translations => translations[lang.value])

  function toggleLang() {
    lang.value = lang.value === 'es' ? 'en' : 'es'
    localStorage.setItem('lang', lang.value)
  }

  return { lang, t, toggleLang }
})
